### PR TITLE
Fix unnecessary omitempty with omitzero

### LINKED ISSUE #195: `requiredfields` linter config with policy ignore makes the linter to not ignore
### Problem statement

With the following config:

```
linters:
  default: none
  enable:
    - kubeapilinter
  settings:
    custom:
      kubeapilinter:
        type: module
        description: Kube API LInter lints Kube like APIs based on API conventions and best practices.
        settings:
          linters:
            disable:
              - "*"
            enable:
              - arrayofstruct
              - conditions
              - defaultorrequired
              - duplicatemarkers
              - integers
              - jsontags
              - maxlength
              - nobools
              - nodurations
              - nofloats
              - nomaps
              - nonullable
              - nophase
              - notimestamp
              - optionalorrequired
              - preferredmarkers
              - requiredfields
              - statusoptional
              - statussubresource
              - uniquemarkers
          lintersConfig:
          #   requiredfields:
          #     omitempty:
          #       policy: Ignore
  exclusions:
    rules:
      - linters:
          - kubeapilinter
        path: api/(konnect|gateway-operator).*
        text: "requiredfields: field .* should have the omitempty tag."

      - linters:
          - kubeapilinter
        path: api/konnect/.*
        text: "requiredfields: field .* does not allow the zero value. It must have the omitzero tag."

      - linters:
          - kubeapilinter
        path: api/konnect/(v1alpha1|v1alpha2)/.*
        text: 'requiredfields: field .* has a valid zero value .* but the validation is not complete'

      - linters:
          - kubeapilinter
        path: api/gateway-operator/v2beta1/shared_types.go
        text: 'requiredfields: field .* has a valid zero value .* but the validation is not complete'

      - linters:
          - kubeapilinter
        path: api/gateway-operator/v2beta1/shared_types.go
        text: 'requiredfields: field Strategy has a valid zero value .* and should be a pointer.'
```

there are no violations.

When the commented out section is uncommented then violations are reported:

```
...
api/gateway-operator/v2beta1/controlplane_types.go:80:2: requiredfields: field DataPlane does not allow the zero value. It must have the omitempty tag. (kubeapilinter)
        DataPlane ControlPlaneDataPlaneTarget `json:"dataplane,omitzero"`

```

### Expected behavior

`requiredfields` linter config with `policy: Ignore` should not trigger violations to be reported.

### PR DESCRIPTION
**Pull request by JoelSpeed**
When we are suggesting `omitzero` for a struct, we should not be suggesting that it has `omitempty` as well. In particular, with the `omitempty` configured to `Ignore`, we previously were suggesting `omitempty` as well, which is confusing.

This PR adjusts that logic and adds test cases to prove that we won't suggest omitempty for a struct we already suggested omitzero for.

CC @pmalek would you be able to see if this fixes your issue

Fixes #195

### CODE REVIEW

File: pkg/analysis/requiredfields/testdata/src/b/a.go [hunk 1]
```diff
@@ -1,39 +1,16 @@
...
-
-	// requiredCorrectField should not be picked up.
-	// +required
-	RequiredCorrectField string `json:"requiredCorrectField"`
-
-	// requiredOmitEmptyField field should be picked up.
+type Foo struct {
 	// +required
-	RequiredOmitEmptyField string `json:"requiredOmitEmptyField,omitempty"` // want "field RequiredOmitEmptyField is marked as required, but has the omitempty tag"
+	RequiredStructWithRequiredFieldWithoutOmitZero StructWithRequiredField `json:"dataplane"` // want "field Foo.RequiredStructWithRequiredFieldWithoutOmitZero does not allow the zero value. It must have the omitzero tag."
```
Comment (sivchari) [inline pkg/analysis/requiredfields/testdata/src/b/a.go]:
```suggestion
	RequiredStructWithRequiredFieldWithoutOmitZero StructWithRequiredField `json:"requiredStructWithRequiredFieldWithoutOmitZero"` // want "field Foo.RequiredStructWithRequiredFieldWithoutOmitZero does not allow the zero value. It must have the omitzero tag."
```

Why do you add another name as json tag ? Is it implicit ?

File: pkg/analysis/requiredfields/testdata/src/b/a.go [hunk 2]
```diff
@@ -1,39 +1,16 @@
-package a
+package c
```
Comment (sivchari) [inline pkg/analysis/requiredfields/testdata/src/b/a.go]:
```suggestion
package b
```

**Review by sivchari — COMMENTED** [review]
/lgtm
/hold

Feel free to merge, if you'd follow up.

**Comment by pmalek** [comment]
@JoelSpeed Sorry it took a while. I've just run version 39194b78f05df0e02014f13ca61b24199bafd6be from you fork on my repo and I'm still getting these errors:

```
api/gateway-operator/v2beta1/controlplane_types.go:275:2: requiredfields: field ControlPlaneDataPlaneTarget.Type does not allow the zero value. It must have the omitempty tag. (kubeapilinter)
	Type ControlPlaneDataPlaneTargetType `json:"type"`
	^
...
```

**Comment by pmalek** [comment]
> @pmalek Can you confirm what config that test was with? On the issue reported you were pointing out a `dataplane` field that was presenting an error, are you still getting a lint issue on the `dataplane` field with this fork?

My bad. Indeed that looks like the original issue disapeared with the version from the fork. 🎉 

I added the following config:

```
issues:
  # Maximum issues count per one linter.
  # Set to 0 to disable.
  # Default: 50
  max-issues-per-linter: 0
  # Maximum count of issues with the same text.
  # Set to 0 to disable.
  # Default: 3
  max-same-issues: 0
```

and

```
linters:
  default: none
  enable:
    - kubeapilinter
  settings:
    custom:
      kubeapilinter:
        type: module
        description: Kube API LInter lints Kube like APIs based on API conventions and best practices.
        settings:
          linters:
            disable:
              - "*"
            enable:
              - arrayofstruct
              - conditions
              - defaultorrequired
              - duplicatemarkers
              - integers
              - jsontags
              - maxlength
              - nobools
              - nodurations
              - nofloats
              - nomaps
              - nonullable
              - nophase
              - notimestamp
              - optionalorrequired
              - preferredmarkers
              - requiredfields
              - statusoptional
              - statussubresource
              - uniquemarkers
          lintersConfig:
            # https://github.com/kubernetes-sigs/kube-api-linter/issues/195
            requiredfields:
              omitempty:
                policy: Ignore
            preferredmarkers:
              markers:
                - preferredIdentifier: "k8s:optional"
                  equivalentIdentifiers:
                    - identifier: "kubebuilder:validation:Optional"
                - preferredIdentifier: "k8s:required"
                  equivalentIdentifiers:
                    - identifier: "kubebuilder:validation:Required"
            conditions:
              isFirstField: Warn
              useProtobuf: Warn
              usePatchStrategy: Warn
            nomaps:
              policy: AllowStringToStringMaps
            optionalOrRequired:
              preferredOptionalMarker: optional
              preferredRequiredMarker: required
```

And now I only see the issues being raised for those fields that do not have neither the `omitempty` nor the `omitzero` tag.

**Comment by pmalek** [comment]
> can you raise a new issue please @pmalek for the second part of this?

Which second part you're referring to here?

As I mentioned in my last comment

> And now I only see the issues being raised for those fields that do not have neither the omitempty nor the omitzero tag.

Which I think it's correct, isn't it? 🤔
