### PR TITLE
Fix jsontags linter to ignore "-" tag

### LINKED ISSUE #43: jsontags: Ignore fields of json:"-"
Similar to #39

### PR DESCRIPTION
**Pull request by sivchari**
close #43 

Once, I reproduced it for #43

### CODE REVIEW

**Review by JoelSpeed — COMMENTED** [review]
@sivchari Are you actively working on a fix? Wondering if we can get this merged prior to the CAPI PR where this came up, WDYT?

**Comment by sivchari** [comment]
@JoelSpeed 
I was not able to proceed because I had a presentation just a few minutes ago.
I'll do it later.
Thanks.

**Comment by sivchari** [comment]
@JoelSpeed 
I'm so sorry to be too late. I added the condition if the Ignored field is true and test cases to check whether it works correctly.

File: pkg/analysis/jsontags/testdata/src/a/a.go [hunk 1]
```diff
@@ -18,6 +18,11 @@ type JSONTagTestStruct struct {
 	JSONTagWithID        string `json:"jsonTagWithID"`
 	JSONTagWithTTL       string `json:"jsonTagWithTTL"`
 	JSONTagWithGiB       string `json:"jsonTagWithGiB"`
+	Ignored              string `json:"-"`
+
+	IgnoredAnonymousStruct struct {
+		NoJSONTag string `json:"noJSONTag"`
```
Comment (JoelSpeed) [inline pkg/analysis/jsontags/testdata/src/a/a.go:24]: This has a json tag?

Comment (sivchari) [reply pkg/analysis/jsontags/testdata/src/a/a.go]: sorry, fixed.

File: pkg/analysis/jsontags/testdata/src/a/a.go [hunk 2]
```diff
@@ -18,6 +18,11 @@ type JSONTagTestStruct struct {
 	JSONTagWithID        string `json:"jsonTagWithID"`
 	JSONTagWithTTL       string `json:"jsonTagWithTTL"`
 	JSONTagWithGiB       string `json:"jsonTagWithGiB"`
+	Ignored              string `json:"-"`
+
+	IgnoredAnonymousStruct struct {
+		A string `json:""` // want "field A has empty json tag"
```
Comment (JoelSpeed) [inline pkg/analysis/jsontags/testdata/src/a/a.go:24]: Don't we want to ignore fields within an ignored struct?

Comment (sivchari) [reply pkg/analysis/jsontags/testdata/src/a/a.go:24]: Make sense to me. Maybe, is it better to use inspect.WithStack ?

Comment (JoelSpeed) [reply pkg/analysis/jsontags/testdata/src/a/a.go:24]: I think it might be yeah, I'm wondering if we want to create a common helper to provider the inpect and filter out things like these fields we don't/can't reach 🤔 That might be a much larger refactor though

Comment (sivchari) [reply pkg/analysis/jsontags/testdata/src/a/a.go:24]: > I think it might be yeah, I'm wondering if we want to create a common helper to provider the inpect and filter out things like these fields we don't/can't reach 🤔 That might be a much larger refactor though

It sounds good, but, as you said, it'll be much larger refactoring.
In here, I'll use WithStack for now.
